/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ro_rasel_jni_StorageJNI */

#ifndef _Included_ro_rasel_jni_StorageJNI
#define _Included_ro_rasel_jni_StorageJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ro_rasel_jni_StorageJNI
 * Method:    getS
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ro_rasel_jni_StorageJNI_getS
  (JNIEnv *, jobject);

/*
 * Class:     ro_rasel_jni_StorageJNI
 * Method:    setS
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ro_rasel_jni_StorageJNI_setS
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
